# The following workflow runs upon publishing a new GitHub release
# It builds the source into a gem and publishes it to RubyGems.org
name: Gem Publication
run-name: Gem Publication (${{github.event.release.tag_name}})
permissions: {}
on:
  release:
    types:
      - published
concurrency: gem_publication
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v3.3.0
      - name: Install project-compatible Ruby
        uses: ruby/setup-ruby@v1.144.2
        with:
          ruby-version: 3.2.0
          bundler: 2.4.1
          bundler-cache: true
      - name: Build and publish gem
        run: bundle exec rake publish
        env:
          GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
